# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'date-suggester-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for date-suggester-iOS
　 pod 'SVGKit'
  pod 'Alamofire', '~> 5.1'
  pod 'AlamofireImage', '~> 4.1'

  target 'date-suggester-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'date-suggester-iOSUITests' do
    # Pods for testing
  end

end
